version: "3.2"

services:
  order-service:
    image: ghcr.io/hildanku/order-service:latest
    container_name: 'order-service'
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_network
  shipping-service:
    image: ghcr.io/hildanku/shipping-service:latest
    container_name: 'shipping-service'
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_network
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rbq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq
    networks:
        - rabbitmq_network
volumes:
  rabbitmq_data:
  rabbitmq_log:

networks:
  rabbitmq_network:
    driver: bridge
