version: "3.2"

services:

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq_submissionakhir'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_network
  order-service:
    image: ghcr.io/hildanku/order-service:latest
    container_name: 'order_service_submissionakhir'
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:15672
    networks:
      - rabbitmq_network
  shipping-service:
    image: ghcr.io/hildanku/shipping-service:latest
    container_name: 'shipping_service_submissionakhir'
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:15672
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
