apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping-service
          image: ghcr.io/hildanku/shipping-service:latest
          env:
            - name: AMQP_URL
              # value diambil dari secret rabbitmq srver
              value: amqp://user:Cnhfkp6njqteT4fE@rabbitmq-server.default.svc.cluster.local:5672
            - name: PORT
              value: "3001"


