apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/data/mongodb'

# line 1 : Deklarasi versi API Kubernetes yang digunakan
# line 2 : menggunakan object PersistenVolume
# line 3 : menginisialisasi metadata
# line 4 : memberikan nama object dengan nama mongo-pv
# line 5 : menginisialisasi metadata spesifikasi
# line 6 : 
# line 7-8 : menentukan kapasitas penyimpanan
# line 9-10 : menentukan hak akses node, ReadWriteOnce artinya volume hanya bisa di read write dalam 1 node saja
# line 11-12 : menentukan path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

