apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongo-credentials
          secret:
            secretName: mongo-secret

        - name: data
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: config
          configMap:
            name: mongo-config
      containers:
      - name: mongo-db
        image: mongo:3
        ports:
          - containerPort: 27017
            name: default-port
        volumeMounts:
          - name: config
            mountPath: /config
          - name: mongo-credentials
            mountPath: /etc/mongo-credentials
          - name: data
            mountPath: /data/db
        env:
          - name: MONGO_INITDB_ROOT_USERNAME_FILE
            value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE
            value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD