apiVersion: apps/v1 # menggunakan apiVersio kubernetes versi apps/v1
kind: Deployment # menggunakan object deployment
metadata:
  name: order # memberi nama deployment
spec:
  replicas: 1 # membuat 1 replika pod saja
  selector:
    matchLabels:
      app: order # memilih label app
  template:
    metadata:
      labels:
        app: order # membuat label app
    spec:
      containers:
        - name: order-service # memberi nama container
          image: ghcr.io/hildanku/order-service:latest # menggunakan image dari Dockerfile yang sudah dibuild
          env: # setting environment variabel
            - name: AMQP_URL
              # value diambil dari secret rabbitmq srver
              value: amqp://user:Cnhfkp6njqteT4fE@rabbitmq-server.default.svc.cluster.local:5672
            - name: PORT
              value: "3000"
